global:
  scrape_interval: 15s
  scrape_timeout: 10s
falcon:
  target: http://localhost:8888/push
exporter:
  targets:
    - http://localhost:9999/metrics
    - http://localhost
    - https://aaa.bbb:111
